spring:
  application:
    name: parkingApp

  hibernate:
    dialect: org.hibernate.dialect.PostgresSQL9Dialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/parking_service
    username: postgres
    password: zaq1@WSX

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    debug: true

  liquibase:
#    drop-first: true
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jwt:
  access-token:
    access-key: CnGY3o5sykUvfkuINeJVjfDp6chuK2pCH12V2cQ9aAQ
    expiration-time: 3600

  refresh-token:
    refresh-key: 8G9J3BQkoFedOClXMXMq6iMWLrBVWw78dTGeaZ7t3eP
    expiration-time: 1_209_600

minio:
  endpoint: http://localhost:9000
  access-key: admin12345
  secret-key: admin12345
  bucket-name: pictures

kafka:
  topics:
    spots: spots
    users: users


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always