
CREATE TABLE public.bookings
(
    total_price numeric(38,2) NOT NULL,
    booking_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    end_at timestamp(6) without time zone NOT NULL,
    rented_spot bigint NOT NULL,
    renter_id bigint NOT NULL,
    start_at timestamp(6) without time zone NOT NULL,
)

CREATE TABLE public.chats
(
    chat_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    consumer_id bigint,
    owner_id bigint,
)

CREATE TABLE public.coordinates
(
    coordinates_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    lat character varying(255),
    lon character varying(255),
)

CREATE TABLE public.credentials
(
    credentials_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password_id bigint NOT NULL,
    phone_number character varying(255),
)

CREATE TABLE public.images
(
    image_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    review_id bigint,
    spot_id bigint,
    external_id character varying(255),
)

CREATE TABLE public.messages
(
    is_read boolean,
    author_id bigint,
    chat_id bigint,
    image_id bigint,
    message_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    read_at timestamp(6) without time zone,
    reply_to_message_id bigint,
    sent_at timestamp(6) without time zone,
    message character varying(255),
)

CREATE TABLE public.passwords
(
    password_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(255),
)

CREATE TABLE public.reviews
(
    rate numeric(38,2),
    author bigint,
    created_at timestamp(6) without time zone,
    review_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    spot_id bigint,
    message character varying(255),
)

CREATE TABLE public.spots
(
    price numeric(38,2),
    rate numeric(38,2),
    created_at timestamp(6) without time zone,
    location_coordinates_id bigint,
    owner_id bigint,
    spot_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address character varying(255),
    description character varying(255),
)

CREATE TABLE public.users
(
    credentials_id bigint,
    user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255),
    name character varying(255),
    surname character varying(255),
)